logging.level.root: INFO

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: productsService
          uri: lb://products-service
          predicates:
            - Path=/api/v1/products/**
        - id: rulesService
          uri: lb://rules-service
          predicates:
            - Path=/api/v1/conditions/**, /api/v1/rules/**
        - id: scoringService
          uri: lb://scoring-service
          predicates:
            - Path=/api/v1/scoring/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      leaseRenewalIntervalInSeconds: 5
      lease-expiration-duration-in-seconds: 5
    preferIpAddress: true
    registryFetchIntervalSeconds: 5
    fetchRegistry: true
