INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 1', 'Electronics', 'Blue', 20.99, 0.5, 10);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 2', 'Clothing', 'Brown', 15.99, 0.4, 100);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 3', 'Food', 'Green', 12.99, 1, 67);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 4', 'Electronics', 'Blue', 25.99, 0.3, 45);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 5', 'Clothing', 'Yellow', 18.99, 0.6, 23);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 6', 'Food', 'Green', 14.99, 0.8, 13);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 7', 'Electronics', 'Blue', 30.99, 0.4, 98);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 8', 'Tools', 'Red', 22.99, 0.5, 78);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 9', 'Food', 'Green', 16.99, 0.9, 56);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 10', 'Sports Equipment', 'Blue', 35.99, 0.3, 33);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 11', 'Toys', 'White', 25.99, 0.4, 56);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 12', 'Gardening Supplies', 'Green', 19.99, 1, 45);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 13', 'Electronics', 'Blue', 40.99, 0.5, 20);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 14', 'Clothing', 'Brown', 30.99, 0.6, 67);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 15', 'Food', 'Green', 25.99, 0.8, 34);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 16', 'Sports Equipment', 'Blue', 45.99, 0.4,49);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 17', 'Clothing', 'Yellow', 35.99, 0.5, 600);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 18', 'Food', 'Green', 29.99, 0.9, 90);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 19', 'Electronics', 'White', 50.99, 0.3, 9);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 20', 'Toys', 'Red', 40.99, 0.4, 67);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 21', 'Toys', 'Yellow', 18.99, 0.6, 56);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 22', 'Electronics', 'Blue', 19.99, 1.2, 34)
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 23', 'Clothing', 'Red', 29.99, 0.8, 250);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 24', 'Furniture', 'Green', 149.99, 20, 35);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 25', 'Toys', 'Yellow', 9.99, 0.5, 19);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 26', 'Tools', 'Black', 39.99, 2.5, 20);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 27', 'Sports Equipment', 'White', 99.99, 5, 200);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 28', 'Gardening Supplies', 'Brown', 19.99, 0.7, 100);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 29', 'Furniture', 'Gray', 149.99, 15, 150);
INSERT INTO products (name, type, color, cost, weight, quantity) VALUES ('Product 30', 'Gardening Supplies', 'Brown', 19.99, 0.7, 900);