logging.level.root: INFO

server:
  port: 8082

spring:
  application:
    name: rules-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:rules
    generate-unique-name: false
    name: products
    username: h2
    password: h2