INSERT INTO conditions (attribute, value, operator) VALUES ('color', 'Blue', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('type', 'Clothing', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('cost', 70, '<=');
INSERT INTO conditions (attribute, value, operator) VALUES ('color', 'Red', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('cost', 20.50, '>=');
INSERT INTO conditions (attribute, value, operator) VALUES ('weight', 3.5, '<');
INSERT INTO conditions (attribute, value, operator) VALUES ('quantity', 1000, '>');
INSERT INTO conditions (attribute, value, operator) VALUES ('color', 'Green', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('type', 'Electronics', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('weight', 0.5, '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('quantity', 200, '<=');
INSERT INTO conditions (attribute, value, operator) VALUES ('color', 'Blue', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('type', 'Food', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('cost', 5, '>=');
INSERT INTO conditions (attribute, value, operator) VALUES ('color', 'Red', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('cost', 20.50, '>=');
INSERT INTO conditions (attribute, value, operator) VALUES ('weight', 2.5, '>=');
INSERT INTO conditions (attribute, value, operator) VALUES ('quantity', 50, '>=');
INSERT INTO conditions (attribute, value, operator) VALUES ('color', 'Brown', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('type', 'Tools', '==');
INSERT INTO conditions (attribute, value, operator) VALUES ('weight', 5, '>');
INSERT INTO conditions (attribute, value, operator) VALUES ('color', 'Green', '==');

INSERT INTO rules (score) VALUES (100);
INSERT INTO rules (score) VALUES (90);
INSERT INTO rules (score) VALUES (80);
INSERT INTO rules (score) VALUES (65);
INSERT INTO rules (score) VALUES (50);
INSERT INTO rules (score) VALUES (50);
INSERT INTO rules (score) VALUES (65);
INSERT INTO rules (score) VALUES (85);
INSERT INTO rules (score) VALUES (90);
INSERT INTO rules (score) VALUES (95);
INSERT INTO rules (score) VALUES (100);
INSERT INTO rules (score) VALUES (100);

INSERT INTO rule_condition(rule_id, condition_id) VALUES (1,1);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (2,4);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (1,3);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (3,5);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (4,9);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (5,7);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (6,17);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (5,2);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (7,4);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (8,13);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (9,5);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (10,19);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (11,18);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (12,4);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (1,8);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (2,6);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (3,10);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (4,15);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (6,13);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (8,11);
INSERT INTO rule_condition(rule_id, condition_id) VALUES (7,20);